# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20171013_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Traveler',
        ),
    ]
