# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20171013_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='hotel_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default='last_name', max_length=30),
            preserve_default=False,
        ),
    ]
