# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20171013_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='phone',
        ),
    ]
